services:
  app:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - inkubasi-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - inkubasi-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app
    networks:
      - inkubasi-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3002:3000"
    depends_on:
      - prometheus
    networks:
      - inkubasi-network

volumes:
  db_data:

networks:
  inkubasi-network:
    driver: bridge
